using System.CommandLine;

using Albatross.CommandLine;

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

using Sonos.Base;
using Sonos.Base.Events.Http;
using Sonos.Cli.Commands;

namespace Sonos.Cli;

internal class Program
{
    static async Task<int> Main(string[] args)
    {
        await using var host = new CommandHost("Sonos CLI utility")
            .RegisterServices(RegisterServices)
            .AddCommands()
            .Parse(args)
            .Build();
        return await host.InvokeAsync();
    }

    static void RegisterServices(ParseResult result, IServiceCollection services)
    {
        // RegisterCommands method is generated by codegen
        services.RegisterCommands();
        // register the rest of the dependency here
        services.AddHttpClient();
        services.AddTransient<ISonosServiceProvider, SonosServiceProvider>();
        //if (args.Contains("events"))
        //{
        //    services.Configure<SonosEventReceiverOptions>(context.Configuration.GetSection("SONOSEVENTS"));
        //    services.AddSingleton<ISonosEventBus, SonosEventReceiver>();

        //    services.AddHostedService(factory => (SonosEventReceiver)factory.GetRequiredService<ISonosEventBus>());
        //}
    }
}