/*
 * Sonos-net VirtualLineInService event parsing
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Sonos.Base.Events.Models;

using Sonos.Base.Services;


#nullable enable
/// <summary>
/// VirtualLineIn is set to might emit these properties in events
/// </summary>
public partial class VirtualLineInEvent: VirtualLineInService.IVirtualLineInEvent {
    public string? AVTransportURIMetaData { get; init; }

    /// <summary>
    /// Parsed version of AVTransportURIMetaData
    /// </summary>
    public Metadata.Didl? AVTransportURIMetaDataObject => Metadata.DidlSerializer.DeserializeMetadata(AVTransportURIMetaData);

    public string? CurrentTrackMetaData { get; init; }

    /// <summary>
    /// Parsed version of CurrentTrackMetaData
    /// </summary>
    public Metadata.Didl? CurrentTrackMetaDataObject => Metadata.DidlSerializer.DeserializeMetadata(CurrentTrackMetaData);

    public string? CurrentTransportActions { get; init; }

    public string? EnqueuedTransportURIMetaData { get; init; }

    /// <summary>
    /// Parsed version of EnqueuedTransportURIMetaData
    /// </summary>
    public Metadata.Didl? EnqueuedTransportURIMetaDataObject => Metadata.DidlSerializer.DeserializeMetadata(EnqueuedTransportURIMetaData);

    public string? LastChange { get; init; }

    internal static VirtualLineInEvent? FromDictionary(Dictionary<string, string>? dic)
    {
        if (dic is null) {
            return null;
        }
        return new VirtualLineInEvent {
            AVTransportURIMetaData = dic.TryGetString(nameof(AVTransportURIMetaData)),
            CurrentTrackMetaData = dic.TryGetString(nameof(CurrentTrackMetaData)),
            CurrentTransportActions = dic.TryGetString(nameof(CurrentTransportActions)),
            EnqueuedTransportURIMetaData = dic.TryGetString(nameof(EnqueuedTransportURIMetaData)),
            LastChange = dic.TryGetString(nameof(LastChange)),
        };
    }
}

