/*
 * Sonos-net GroupRenderingControlService event parsing
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Sonos.Base.Events.Http.Models;

using Sonos.Base.Services;


#nullable enable
/// <summary>
/// GroupRenderingControl is set to might emit these properties in events
/// </summary>
public partial class GroupRenderingControlEvent: GroupRenderingControlService.IGroupRenderingControlEvent {
    public bool? GroupMute { get; init; }

    public int? GroupVolume { get; init; }

    public bool? GroupVolumeChangeable { get; init; }

    internal static GroupRenderingControlEvent? FromDictionary(Dictionary<string, string>? dic)
    {
        if (dic is null) {
            return null;
        }
        return new GroupRenderingControlEvent {
            GroupMute = dic.TryGetBool(nameof(GroupMute)),
            GroupVolume = dic.TryGetInt(nameof(GroupVolume)),
            GroupVolumeChangeable = dic.TryGetBool(nameof(GroupVolumeChangeable)),
        };
    }
}

