/*
 * Sonos-net - SonosDevice
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Sonos.Base;

using Sonos.Base.Services;
public partial class SonosDevice
{
    #nullable enable
    private AlarmClockService? _alarmclock;
    /// <summary>
    /// Auto initialized AlarmClock Service for this device
    /// </summary>
    public AlarmClockService AlarmClockService => _alarmclock ??= new AlarmClockService(ServiceOptions);

    private AudioInService? _audioin;
    /// <summary>
    /// Auto initialized AudioIn Service for this device
    /// </summary>
    public AudioInService AudioInService => _audioin ??= new AudioInService(ServiceOptions);

    private AVTransportService? _avtransport;
    /// <summary>
    /// Auto initialized AVTransport Service for this device
    /// </summary>
    public AVTransportService AVTransportService => _avtransport ??= new AVTransportService(ServiceOptions);

    private ConnectionManagerService? _connectionmanager;
    /// <summary>
    /// Auto initialized ConnectionManager Service for this device
    /// </summary>
    public ConnectionManagerService ConnectionManagerService => _connectionmanager ??= new ConnectionManagerService(ServiceOptions);

    private ContentDirectoryService? _contentdirectory;
    /// <summary>
    /// Auto initialized ContentDirectory Service for this device
    /// </summary>
    public ContentDirectoryService ContentDirectoryService => _contentdirectory ??= new ContentDirectoryService(ServiceOptions);

    private DevicePropertiesService? _deviceproperties;
    /// <summary>
    /// Auto initialized DeviceProperties Service for this device
    /// </summary>
    public DevicePropertiesService DevicePropertiesService => _deviceproperties ??= new DevicePropertiesService(ServiceOptions);

    private GroupManagementService? _groupmanagement;
    /// <summary>
    /// Auto initialized GroupManagement Service for this device
    /// </summary>
    public GroupManagementService GroupManagementService => _groupmanagement ??= new GroupManagementService(ServiceOptions);

    private GroupRenderingControlService? _grouprenderingcontrol;
    /// <summary>
    /// Auto initialized GroupRenderingControl Service for this device
    /// </summary>
    public GroupRenderingControlService GroupRenderingControlService => _grouprenderingcontrol ??= new GroupRenderingControlService(ServiceOptions);

    private HTControlService? _htcontrol;
    /// <summary>
    /// Auto initialized HTControl Service for this device
    /// </summary>
    public HTControlService HTControlService => _htcontrol ??= new HTControlService(ServiceOptions);

    private MusicServicesService? _musicservices;
    /// <summary>
    /// Auto initialized MusicServices Service for this device
    /// </summary>
    public MusicServicesService MusicServicesService => _musicservices ??= new MusicServicesService(ServiceOptions);

    private QPlayService? _qplay;
    /// <summary>
    /// Auto initialized QPlay Service for this device
    /// </summary>
    public QPlayService QPlayService => _qplay ??= new QPlayService(ServiceOptions);

    private QueueService? _queue;
    /// <summary>
    /// Auto initialized Queue Service for this device
    /// </summary>
    public QueueService QueueService => _queue ??= new QueueService(ServiceOptions);

    private RenderingControlService? _renderingcontrol;
    /// <summary>
    /// Auto initialized RenderingControl Service for this device
    /// </summary>
    public RenderingControlService RenderingControlService => _renderingcontrol ??= new RenderingControlService(ServiceOptions);

    private SystemPropertiesService? _systemproperties;
    /// <summary>
    /// Auto initialized SystemProperties Service for this device
    /// </summary>
    public SystemPropertiesService SystemPropertiesService => _systemproperties ??= new SystemPropertiesService(ServiceOptions);

    private VirtualLineInService? _virtuallinein;
    /// <summary>
    /// Auto initialized VirtualLineIn Service for this device
    /// </summary>
    public VirtualLineInService VirtualLineInService => _virtuallinein ??= new VirtualLineInService(ServiceOptions);

    private ZoneGroupTopologyService? _zonegrouptopology;
    /// <summary>
    /// Auto initialized ZoneGroupTopology Service for this device
    /// </summary>
    public ZoneGroupTopologyService ZoneGroupTopologyService => _zonegrouptopology ??= new ZoneGroupTopologyService(ServiceOptions);

    private void DisposeServices()
    {
        _alarmclock?.Dispose();
        _audioin?.Dispose();
        _avtransport?.Dispose();
        _connectionmanager?.Dispose();
        _contentdirectory?.Dispose();
        _deviceproperties?.Dispose();
        _groupmanagement?.Dispose();
        _grouprenderingcontrol?.Dispose();
        _htcontrol?.Dispose();
        _musicservices?.Dispose();
        _qplay?.Dispose();
        _queue?.Dispose();
        _renderingcontrol?.Dispose();
        _systemproperties?.Dispose();
        _virtuallinein?.Dispose();
        _zonegrouptopology?.Dispose();
    }
    #nullable disable

    private async ValueTask DisposeServicesAsync()
    {
        if (_alarmclock is not null)
        {
            await _alarmclock.DisposeAsync();
        }
        if (_audioin is not null)
        {
            await _audioin.DisposeAsync();
        }
        if (_avtransport is not null)
        {
            await _avtransport.DisposeAsync();
        }
        if (_connectionmanager is not null)
        {
            await _connectionmanager.DisposeAsync();
        }
        if (_contentdirectory is not null)
        {
            await _contentdirectory.DisposeAsync();
        }
        if (_deviceproperties is not null)
        {
            await _deviceproperties.DisposeAsync();
        }
        if (_groupmanagement is not null)
        {
            await _groupmanagement.DisposeAsync();
        }
        if (_grouprenderingcontrol is not null)
        {
            await _grouprenderingcontrol.DisposeAsync();
        }
        if (_htcontrol is not null)
        {
            await _htcontrol.DisposeAsync();
        }
        if (_musicservices is not null)
        {
            await _musicservices.DisposeAsync();
        }
        if (_qplay is not null)
        {
            await _qplay.DisposeAsync();
        }
        if (_queue is not null)
        {
            await _queue.DisposeAsync();
        }
        if (_renderingcontrol is not null)
        {
            await _renderingcontrol.DisposeAsync();
        }
        if (_systemproperties is not null)
        {
            await _systemproperties.DisposeAsync();
        }
        if (_virtuallinein is not null)
        {
            await _virtuallinein.DisposeAsync();
        }
        if (_zonegrouptopology is not null)
        {
            await _zonegrouptopology.DisposeAsync();
        }
    }
}
