/*
 * Sonos-net AlarmClockService
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated/>
namespace Sonos.Web.SonosServices;

using Microsoft.AspNetCore.Mvc;
using Sonos.Base;
using Sonos.Base.Services;

internal static class AlarmClockApi
{
    private const string SERVICE_NAME = "AlarmClock";
    private const string SERVICE_NAME_KEBAB = "alarm-clock";
    internal static RouteGroupBuilder MapAlarmClockApi(this WebApplication webApplication)
    {
        var group = webApplication
            .MapGroup("/api/speakers/{speakerId}/alarmclock")
            .WithTags("UPNP AlarmClock")
            .WithGroupName("upnp-alarm-clock");

        group.MapPost("/createalarm", CreateAlarmAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "CreateAlarm", SERVICE_NAME_KEBAB, "Create a single alarm, all properties are required")
            .Produces<AlarmClockService.CreateAlarmResponse>(200);

        group.MapPost("/destroyalarm", DestroyAlarmAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "DestroyAlarm", SERVICE_NAME_KEBAB, "Delete an alarm")
            .Produces<bool>(200);

        group.MapGet("/getdailyindexrefreshtime", GetDailyIndexRefreshTimeAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetDailyIndexRefreshTime", SERVICE_NAME_KEBAB, null)
            .Produces<AlarmClockService.GetDailyIndexRefreshTimeResponse>(200);

        group.MapGet("/getformat", GetFormatAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetFormat", SERVICE_NAME_KEBAB, null)
            .Produces<AlarmClockService.GetFormatResponse>(200);

        group.MapPost("/gethouseholdtimeatstamp", GetHouseholdTimeAtStampAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetHouseholdTimeAtStamp", SERVICE_NAME_KEBAB, null)
            .Produces<AlarmClockService.GetHouseholdTimeAtStampResponse>(200);

        group.MapGet("/gettimenow", GetTimeNowAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetTimeNow", SERVICE_NAME_KEBAB, null)
            .Produces<AlarmClockService.GetTimeNowResponse>(200);

        group.MapGet("/gettimeserver", GetTimeServerAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetTimeServer", SERVICE_NAME_KEBAB, null)
            .Produces<AlarmClockService.GetTimeServerResponse>(200);

        group.MapGet("/gettimezone", GetTimeZoneAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetTimeZone", SERVICE_NAME_KEBAB, null)
            .Produces<AlarmClockService.GetTimeZoneResponse>(200);

        group.MapGet("/gettimezoneandrule", GetTimeZoneAndRuleAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetTimeZoneAndRule", SERVICE_NAME_KEBAB, null)
            .Produces<AlarmClockService.GetTimeZoneAndRuleResponse>(200);

        group.MapPost("/gettimezonerule", GetTimeZoneRuleAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetTimeZoneRule", SERVICE_NAME_KEBAB, null)
            .Produces<AlarmClockService.GetTimeZoneRuleResponse>(200);

        group.MapGet("/listalarms", ListAlarmsAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "ListAlarms", SERVICE_NAME_KEBAB, "Get the AlarmList as XML")
            .Produces<AlarmClockService.ListAlarmsResponse>(200);

        group.MapPost("/setdailyindexrefreshtime", SetDailyIndexRefreshTimeAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetDailyIndexRefreshTime", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/setformat", SetFormatAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetFormat", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/settimenow", SetTimeNowAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetTimeNow", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/settimeserver", SetTimeServerAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetTimeServer", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/settimezone", SetTimeZoneAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetTimeZone", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/updatealarm", UpdateAlarmAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "UpdateAlarm", SERVICE_NAME_KEBAB, "Update an alarm, all parameters are required.")
            .Produces<bool>(200);

        return group;
    }

    private static async Task<IResult> CreateAlarmAsync(
        [FromRoute]string speakerId,
        [FromBody]AlarmClockService.CreateAlarmRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.CreateAlarm(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> DestroyAlarmAsync(
        [FromRoute]string speakerId,
        [FromBody]AlarmClockService.DestroyAlarmRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.DestroyAlarm(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetDailyIndexRefreshTimeAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.GetDailyIndexRefreshTime(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetFormatAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.GetFormat(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetHouseholdTimeAtStampAsync(
        [FromRoute]string speakerId,
        [FromBody]AlarmClockService.GetHouseholdTimeAtStampRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.GetHouseholdTimeAtStamp(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetTimeNowAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.GetTimeNow(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetTimeServerAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.GetTimeServer(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetTimeZoneAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.GetTimeZone(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetTimeZoneAndRuleAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.GetTimeZoneAndRule(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetTimeZoneRuleAsync(
        [FromRoute]string speakerId,
        [FromBody]AlarmClockService.GetTimeZoneRuleRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.GetTimeZoneRule(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> ListAlarmsAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.ListAlarms(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetDailyIndexRefreshTimeAsync(
        [FromRoute]string speakerId,
        [FromBody]AlarmClockService.SetDailyIndexRefreshTimeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.SetDailyIndexRefreshTime(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetFormatAsync(
        [FromRoute]string speakerId,
        [FromBody]AlarmClockService.SetFormatRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.SetFormat(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetTimeNowAsync(
        [FromRoute]string speakerId,
        [FromBody]AlarmClockService.SetTimeNowRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.SetTimeNow(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetTimeServerAsync(
        [FromRoute]string speakerId,
        [FromBody]AlarmClockService.SetTimeServerRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.SetTimeServer(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetTimeZoneAsync(
        [FromRoute]string speakerId,
        [FromBody]AlarmClockService.SetTimeZoneRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.SetTimeZone(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> UpdateAlarmAsync(
        [FromRoute]string speakerId,
        [FromBody]AlarmClockService.UpdateAlarmRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.AlarmClockService.UpdateAlarm(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }
}
