/*
 * Sonos-net ConnectionManagerService
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Sonos.Web.SonosServices;

using Microsoft.AspNetCore.Mvc;
using Sonos.Base;
using Sonos.Base.Services;

internal static class ConnectionManagerApi
{
    private const string SERVICE_NAME = "ConnectionManager";
    private const string SERVICE_NAME_KEBAB = "connection-manager";
    internal static RouteGroupBuilder MapConnectionManagerApi(this WebApplication webApplication)
    {
        var group = webApplication
            .MapGroup("/api/speakers/{speakerId}/connectionmanager")
            .WithTags("UPNP ConnectionManager")
            .WithGroupName("upnp-connection-manager");

        group.MapGet("/getcurrentconnectionids", GetCurrentConnectionIDsAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetCurrentConnectionIDs", SERVICE_NAME_KEBAB, null)
            .Produces<ConnectionManagerService.GetCurrentConnectionIDsResponse>(200);

        group.MapPost("/getcurrentconnectioninfo", GetCurrentConnectionInfoAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetCurrentConnectionInfo", SERVICE_NAME_KEBAB, null)
            .Produces<ConnectionManagerService.GetCurrentConnectionInfoResponse>(200);

        group.MapGet("/getprotocolinfo", GetProtocolInfoAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetProtocolInfo", SERVICE_NAME_KEBAB, null)
            .Produces<ConnectionManagerService.GetProtocolInfoResponse>(200);

        return group;
    }

    private static async Task<IResult> GetCurrentConnectionIDsAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.ConnectionManagerService.GetCurrentConnectionIDs(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetCurrentConnectionInfoAsync(
        [FromRoute]string speakerId,
        [FromBody]ConnectionManagerService.GetCurrentConnectionInfoRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.ConnectionManagerService.GetCurrentConnectionInfo(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetProtocolInfoAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.ConnectionManagerService.GetProtocolInfo(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }
}
