/*
 * Sonos-net ContentDirectoryService
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated/>
namespace Sonos.Web.SonosServices;

using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using Sonos.Base;
using Sonos.Base.Services;
using Sonos.Web.Filters;

internal static class ContentDirectoryApi
{
    private const string SERVICE_NAME = "ContentDirectory";
    private const string SERVICE_NAME_KEBAB = "content-directory";
    internal static RouteGroupBuilder MapContentDirectoryApi(this WebApplication webApplication)
    {
        var group = webApplication
            .MapGroup("/api/speakers/{speakerId}/contentdirectory")
            .WithTags("UPNP ContentDirectory")
            .WithGroupName("upnp-content-directory");

        group.MapPost("/browse", BrowseAsync)
            .Produces<ContentDirectoryService.BrowseResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "Browse", SERVICE_NAME_KEBAB, "Browse for content: Music library (A), share(S:), Sonos playlists(SQ:), Sonos favorites(FV:2), radio stations(R:0/0), radio shows(R:0/1), queue(Q:)). Recommendation: Send one request, check the &#x60;TotalMatches&#x60; and - if necessary - do additional requests with higher &#x60;StartingIndex&#x60;. In case of duplicates only the first is returned! Example: albums with same title, even if artists are different")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/createobject", CreateObjectAsync)
            .Produces<ContentDirectoryService.CreateObjectResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "CreateObject", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/destroyobject", DestroyObjectAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "DestroyObject", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/findprefix", FindPrefixAsync)
            .Produces<ContentDirectoryService.FindPrefixResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "FindPrefix", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getalbumartistdisplayoption", GetAlbumArtistDisplayOptionAsync)
            .Produces<ContentDirectoryService.GetAlbumArtistDisplayOptionResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetAlbumArtistDisplayOption", SERVICE_NAME_KEBAB, "Get the current album art display option such as &#x60;WMP&#x60;, &#x60;ITUNES&#x60; or &#x60;NONE&#x60;")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/getallprefixlocations", GetAllPrefixLocationsAsync)
            .Produces<ContentDirectoryService.GetAllPrefixLocationsResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetAllPrefixLocations", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getbrowseable", GetBrowseableAsync)
            .Produces<ContentDirectoryService.GetBrowseableResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetBrowseable", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getlastindexchange", GetLastIndexChangeAsync)
            .Produces<ContentDirectoryService.GetLastIndexChangeResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetLastIndexChange", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getsearchcapabilities", GetSearchCapabilitiesAsync)
            .Produces<ContentDirectoryService.GetSearchCapabilitiesResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetSearchCapabilities", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getshareindexinprogress", GetShareIndexInProgressAsync)
            .Produces<ContentDirectoryService.GetShareIndexInProgressResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetShareIndexInProgress", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getsortcapabilities", GetSortCapabilitiesAsync)
            .Produces<ContentDirectoryService.GetSortCapabilitiesResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetSortCapabilities", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getsystemupdateid", GetSystemUpdateIDAsync)
            .Produces<ContentDirectoryService.GetSystemUpdateIDResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetSystemUpdateID", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/refreshshareindex", RefreshShareIndexAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "RefreshShareIndex", SERVICE_NAME_KEBAB, "Updates the music library (share) index")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/requestresort", RequestResortAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "RequestResort", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setbrowseable", SetBrowseableAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetBrowseable", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/updateobject", UpdateObjectAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "UpdateObject", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        return group;
    }

    private static async Task<IResult> BrowseAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory Browse body")]ContentDirectoryService.BrowseRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.Browse(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> CreateObjectAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory CreateObject body")]ContentDirectoryService.CreateObjectRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.CreateObject(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> DestroyObjectAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory DestroyObject body")]ContentDirectoryService.DestroyObjectRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.DestroyObject(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> FindPrefixAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory FindPrefix body")]ContentDirectoryService.FindPrefixRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.FindPrefix(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetAlbumArtistDisplayOptionAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.GetAlbumArtistDisplayOption(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetAllPrefixLocationsAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory GetAllPrefixLocations body")]ContentDirectoryService.GetAllPrefixLocationsRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.GetAllPrefixLocations(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetBrowseableAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.GetBrowseable(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetLastIndexChangeAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.GetLastIndexChange(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetSearchCapabilitiesAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.GetSearchCapabilities(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetShareIndexInProgressAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.GetShareIndexInProgress(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetSortCapabilitiesAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.GetSortCapabilities(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetSystemUpdateIDAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.GetSystemUpdateID(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> RefreshShareIndexAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory RefreshShareIndex body")]ContentDirectoryService.RefreshShareIndexRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.RefreshShareIndex(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> RequestResortAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory RequestResort body")]ContentDirectoryService.RequestResortRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.RequestResort(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetBrowseableAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetBrowseable body")]ContentDirectoryService.SetBrowseableRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.SetBrowseable(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> UpdateObjectAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory UpdateObject body")]ContentDirectoryService.UpdateObjectRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.ContentDirectoryService.UpdateObject(body, cancellationToken);
        return Results.Ok(result);
    }
}
