/*
 * Sonos-net DevicePropertiesService
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated/>
namespace Sonos.Web.SonosServices;

using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using Sonos.Base;
using Sonos.Base.Services;
using Sonos.Web.Filters;

internal static class DevicePropertiesApi
{
    private const string SERVICE_NAME = "DeviceProperties";
    private const string SERVICE_NAME_KEBAB = "device-properties";
    internal static RouteGroupBuilder MapDevicePropertiesApi(this WebApplication webApplication)
    {
        var group = webApplication
            .MapGroup("/api/speakers/{speakerId}/deviceproperties")
            .WithTags("UPNP DeviceProperties")
            .WithGroupName("upnp-device-properties");

        group.MapPost("/addbondedzones", AddBondedZonesAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "AddBondedZones", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/addhtsatellite", AddHTSatelliteAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "AddHTSatellite", SERVICE_NAME_KEBAB, "Adds satellites and/or a sub woofer to a (main) player. The satellites become hidden. The main player RINCON_* is mandatory. RR: right - rear, LF: left - front, SW: subwoofer")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/createstereopair", CreateStereoPairAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "CreateStereoPair", SERVICE_NAME_KEBAB, "Create a stereo pair (left, right speakers), right one becomes hidden")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/enterconfigmode", EnterConfigModeAsync)
            .Produces<DevicePropertiesService.EnterConfigModeResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "EnterConfigMode", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/exitconfigmode", ExitConfigModeAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "ExitConfigMode", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/getautoplaylinkedzones", GetAutoplayLinkedZonesAsync)
            .Produces<DevicePropertiesService.GetAutoplayLinkedZonesResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetAutoplayLinkedZones", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/getautoplayroomuuid", GetAutoplayRoomUUIDAsync)
            .Produces<DevicePropertiesService.GetAutoplayRoomUUIDResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetAutoplayRoomUUID", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/getautoplayvolume", GetAutoplayVolumeAsync)
            .Produces<DevicePropertiesService.GetAutoplayVolumeResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetAutoplayVolume", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getbuttonlockstate", GetButtonLockStateAsync)
            .Produces<DevicePropertiesService.GetButtonLockStateResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetButtonLockState", SERVICE_NAME_KEBAB, "Get the current button lock state")
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getbuttonstate", GetButtonStateAsync)
            .Produces<DevicePropertiesService.GetButtonStateResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetButtonState", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/gethouseholdid", GetHouseholdIDAsync)
            .Produces<DevicePropertiesService.GetHouseholdIDResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetHouseholdID", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/gethtforwardstate", GetHTForwardStateAsync)
            .Produces<DevicePropertiesService.GetHTForwardStateResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetHTForwardState", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getledstate", GetLEDStateAsync)
            .Produces<DevicePropertiesService.GetLEDStateResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetLEDState", SERVICE_NAME_KEBAB, "Get the current LED state")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/getuseautoplayvolume", GetUseAutoplayVolumeAsync)
            .Produces<DevicePropertiesService.GetUseAutoplayVolumeResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetUseAutoplayVolume", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getzoneattributes", GetZoneAttributesAsync)
            .Produces<DevicePropertiesService.GetZoneAttributesResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetZoneAttributes", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getzoneinfo", GetZoneInfoAsync)
            .Produces<DevicePropertiesService.GetZoneInfoResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetZoneInfo", SERVICE_NAME_KEBAB, "Get information about this specific speaker")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/removebondedzones", RemoveBondedZonesAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "RemoveBondedZones", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/removehtsatellite", RemoveHTSatelliteAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "RemoveHTSatellite", SERVICE_NAME_KEBAB, "Removes a satellite or a sub woofer from (main) player. The satellite becomes visible.")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/roomdetectionstartchirping", RoomDetectionStartChirpingAsync)
            .Produces<DevicePropertiesService.RoomDetectionStartChirpingResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "RoomDetectionStartChirping", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/roomdetectionstopchirping", RoomDetectionStopChirpingAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "RoomDetectionStopChirping", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/separatestereopair", SeparateStereoPairAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SeparateStereoPair", SERVICE_NAME_KEBAB, "Separate a stereo pair")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setautoplaylinkedzones", SetAutoplayLinkedZonesAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetAutoplayLinkedZones", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setautoplayroomuuid", SetAutoplayRoomUUIDAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetAutoplayRoomUUID", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setautoplayvolume", SetAutoplayVolumeAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetAutoplayVolume", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setbuttonlockstate", SetButtonLockStateAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetButtonLockState", SERVICE_NAME_KEBAB, "Set the button lock state")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setledstate", SetLEDStateAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetLEDState", SERVICE_NAME_KEBAB, "Set the LED state")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setuseautoplayvolume", SetUseAutoplayVolumeAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetUseAutoplayVolume", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setzoneattributes", SetZoneAttributesAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetZoneAttributes", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        return group;
    }

    private static async Task<IResult> AddBondedZonesAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory AddBondedZones body")]DevicePropertiesService.AddBondedZonesRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.AddBondedZones(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> AddHTSatelliteAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory AddHTSatellite body")]DevicePropertiesService.AddHTSatelliteRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.AddHTSatellite(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> CreateStereoPairAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory CreateStereoPair body")]DevicePropertiesService.CreateStereoPairRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.CreateStereoPair(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> EnterConfigModeAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory EnterConfigMode body")]DevicePropertiesService.EnterConfigModeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.EnterConfigMode(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> ExitConfigModeAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory ExitConfigMode body")]DevicePropertiesService.ExitConfigModeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.ExitConfigMode(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetAutoplayLinkedZonesAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory GetAutoplayLinkedZones body")]DevicePropertiesService.GetAutoplayLinkedZonesRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.GetAutoplayLinkedZones(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetAutoplayRoomUUIDAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory GetAutoplayRoomUUID body")]DevicePropertiesService.GetAutoplayRoomUUIDRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.GetAutoplayRoomUUID(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetAutoplayVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory GetAutoplayVolume body")]DevicePropertiesService.GetAutoplayVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.GetAutoplayVolume(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetButtonLockStateAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.GetButtonLockState(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetButtonStateAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.GetButtonState(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetHouseholdIDAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.GetHouseholdID(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetHTForwardStateAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.GetHTForwardState(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetLEDStateAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.GetLEDState(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetUseAutoplayVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory GetUseAutoplayVolume body")]DevicePropertiesService.GetUseAutoplayVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.GetUseAutoplayVolume(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetZoneAttributesAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.GetZoneAttributes(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetZoneInfoAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.GetZoneInfo(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> RemoveBondedZonesAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory RemoveBondedZones body")]DevicePropertiesService.RemoveBondedZonesRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.RemoveBondedZones(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> RemoveHTSatelliteAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory RemoveHTSatellite body")]DevicePropertiesService.RemoveHTSatelliteRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.RemoveHTSatellite(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> RoomDetectionStartChirpingAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory RoomDetectionStartChirping body")]DevicePropertiesService.RoomDetectionStartChirpingRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.RoomDetectionStartChirping(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> RoomDetectionStopChirpingAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory RoomDetectionStopChirping body")]DevicePropertiesService.RoomDetectionStopChirpingRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.RoomDetectionStopChirping(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SeparateStereoPairAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SeparateStereoPair body")]DevicePropertiesService.SeparateStereoPairRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.SeparateStereoPair(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetAutoplayLinkedZonesAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetAutoplayLinkedZones body")]DevicePropertiesService.SetAutoplayLinkedZonesRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.SetAutoplayLinkedZones(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetAutoplayRoomUUIDAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetAutoplayRoomUUID body")]DevicePropertiesService.SetAutoplayRoomUUIDRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.SetAutoplayRoomUUID(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetAutoplayVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetAutoplayVolume body")]DevicePropertiesService.SetAutoplayVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.SetAutoplayVolume(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetButtonLockStateAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetButtonLockState body")]DevicePropertiesService.SetButtonLockStateRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.SetButtonLockState(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetLEDStateAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetLEDState body")]DevicePropertiesService.SetLEDStateRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.SetLEDState(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetUseAutoplayVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetUseAutoplayVolume body")]DevicePropertiesService.SetUseAutoplayVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.SetUseAutoplayVolume(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetZoneAttributesAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetZoneAttributes body")]DevicePropertiesService.SetZoneAttributesRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.DevicePropertiesService.SetZoneAttributes(body, cancellationToken);
        return Results.Ok(result);
    }
}
