/*
 * Sonos-net GroupRenderingControlService
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Sonos.Web.SonosServices;

using Microsoft.AspNetCore.Mvc;
using Sonos.Base;
using Sonos.Base.Services;

internal static class GroupRenderingControlApi
{
    private const string SERVICE_NAME = "GroupRenderingControl";
    private const string SERVICE_NAME_KEBAB = "group-rendering-control";
    internal static RouteGroupBuilder MapGroupRenderingControlApi(this WebApplication webApplication)
    {
        var group = webApplication
            .MapGroup("/api/speakers/{speakerId}/grouprenderingcontrol")
            .WithTags("UPNP GroupRenderingControl")
            .WithGroupName("upnp-group-rendering-control");

        group.MapGet("/getgroupmute", GetGroupMuteAsync)

            .WithSonosServiceDescription(SERVICE_NAME, "GetGroupMute", SERVICE_NAME_KEBAB, "Get the group mute state.")
            .Produces<GroupRenderingControlService.GetGroupMuteResponse>(200);

        group.MapGet("/getgroupvolume", GetGroupVolumeAsync)

            .WithSonosServiceDescription(SERVICE_NAME, "GetGroupVolume", SERVICE_NAME_KEBAB, "Get the group volume.")
            .Produces<GroupRenderingControlService.GetGroupVolumeResponse>(200);

        group.MapPost("/setgroupmute", SetGroupMuteAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetGroupMute", SERVICE_NAME_KEBAB, "(Un-/)Mute the entire group")
            .Produces<bool>(200);

        group.MapPost("/setgroupvolume", SetGroupVolumeAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetGroupVolume", SERVICE_NAME_KEBAB, "Change group volume. Players volume will be changed proportionally based on last snapshot")
            .Produces<bool>(200);

        group.MapPost("/setrelativegroupvolume", SetRelativeGroupVolumeAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetRelativeGroupVolume", SERVICE_NAME_KEBAB, "Relatively change group volume - returns final group volume. Players volume will be changed proportionally based on last snapshot")
            .Produces<GroupRenderingControlService.SetRelativeGroupVolumeResponse>(200);

        group.MapGet("/snapshotgroupvolume", SnapshotGroupVolumeAsync)

            .WithSonosServiceDescription(SERVICE_NAME, "SnapshotGroupVolume", SERVICE_NAME_KEBAB, "Creates a new group volume snapshot,  the volume ratio between all players. It is used by SetGroupVolume and SetRelativeGroupVolume")
            .Produces<bool>(200);

        return group;
    }

    private static async Task<IResult> GetGroupMuteAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.GroupRenderingControlService.GetGroupMute(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetGroupVolumeAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.GroupRenderingControlService.GetGroupVolume(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetGroupMuteAsync(
        [FromRoute]string speakerId,
        [FromBody]GroupRenderingControlService.SetGroupMuteRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.GroupRenderingControlService.SetGroupMute(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetGroupVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody]GroupRenderingControlService.SetGroupVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.GroupRenderingControlService.SetGroupVolume(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetRelativeGroupVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody]GroupRenderingControlService.SetRelativeGroupVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.GroupRenderingControlService.SetRelativeGroupVolume(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SnapshotGroupVolumeAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.GroupRenderingControlService.SnapshotGroupVolume(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }
}
