/*
 * Sonos-net GroupManagementService
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated/>
namespace Sonos.Web.SonosServices;

using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using Sonos.Base;
using Sonos.Base.Services;
using Sonos.Web.Filters;

internal static class GroupManagementApi
{
    private const string SERVICE_NAME = "GroupManagement";
    private const string SERVICE_NAME_KEBAB = "group-management";
    internal static RouteGroupBuilder MapGroupManagementApi(this WebApplication webApplication)
    {
        var group = webApplication
            .MapGroup("/api/speakers/{speakerId}/groupmanagement")
            .WithTags("UPNP GroupManagement")
            .WithGroupName("upnp-group-management");

        group.MapPost("/addmember", AddMemberAsync)
            .Produces<GroupManagementService.AddMemberResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "AddMember", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/removemember", RemoveMemberAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "RemoveMember", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/reporttrackbufferingresult", ReportTrackBufferingResultAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "ReportTrackBufferingResult", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setsourceareaids", SetSourceAreaIdsAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetSourceAreaIds", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        return group;
    }

    private static async Task<IResult> AddMemberAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory AddMember body")]GroupManagementService.AddMemberRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.GroupManagementService.AddMember(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> RemoveMemberAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory RemoveMember body")]GroupManagementService.RemoveMemberRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.GroupManagementService.RemoveMember(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> ReportTrackBufferingResultAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory ReportTrackBufferingResult body")]GroupManagementService.ReportTrackBufferingResultRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.GroupManagementService.ReportTrackBufferingResult(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetSourceAreaIdsAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetSourceAreaIds body")]GroupManagementService.SetSourceAreaIdsRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.GroupManagementService.SetSourceAreaIds(body, cancellationToken);
        return Results.Ok(result);
    }
}
