/*
 * Sonos-net HTControlService
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated/>
namespace Sonos.Web.SonosServices;

using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using Sonos.Base;
using Sonos.Base.Services;
using Sonos.Web.Filters;

internal static class HTControlApi
{
    private const string SERVICE_NAME = "HTControl";
    private const string SERVICE_NAME_KEBAB = "ht-control";
    internal static RouteGroupBuilder MapHTControlApi(this WebApplication webApplication)
    {
        var group = webApplication
            .MapGroup("/api/speakers/{speakerId}/htcontrol")
            .WithTags("UPNP HTControl")
            .WithGroupName("upnp-ht-control");

        group.MapPost("/commitlearnedircodes", CommitLearnedIRCodesAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "CommitLearnedIRCodes", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getirrepeaterstate", GetIRRepeaterStateAsync)
            .Produces<HTControlService.GetIRRepeaterStateResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetIRRepeaterState", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getledfeedbackstate", GetLEDFeedbackStateAsync)
            .Produces<HTControlService.GetLEDFeedbackStateResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetLEDFeedbackState", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/identifyirremote", IdentifyIRRemoteAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "IdentifyIRRemote", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/isremoteconfigured", IsRemoteConfiguredAsync)
            .Produces<HTControlService.IsRemoteConfiguredResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "IsRemoteConfigured", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/learnircode", LearnIRCodeAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "LearnIRCode", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setirrepeaterstate", SetIRRepeaterStateAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetIRRepeaterState", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setledfeedbackstate", SetLEDFeedbackStateAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetLEDFeedbackState", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        return group;
    }

    private static async Task<IResult> CommitLearnedIRCodesAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory CommitLearnedIRCodes body")]HTControlService.CommitLearnedIRCodesRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.HTControlService.CommitLearnedIRCodes(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetIRRepeaterStateAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.HTControlService.GetIRRepeaterState(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetLEDFeedbackStateAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.HTControlService.GetLEDFeedbackState(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> IdentifyIRRemoteAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory IdentifyIRRemote body")]HTControlService.IdentifyIRRemoteRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.HTControlService.IdentifyIRRemote(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> IsRemoteConfiguredAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.HTControlService.IsRemoteConfigured(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> LearnIRCodeAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory LearnIRCode body")]HTControlService.LearnIRCodeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.HTControlService.LearnIRCode(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetIRRepeaterStateAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetIRRepeaterState body")]HTControlService.SetIRRepeaterStateRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.HTControlService.SetIRRepeaterState(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetLEDFeedbackStateAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetLEDFeedbackState body")]HTControlService.SetLEDFeedbackStateRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.HTControlService.SetLEDFeedbackState(body, cancellationToken);
        return Results.Ok(result);
    }
}
