/*
 * Sonos-net MusicServicesService
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated/>
namespace Sonos.Web.SonosServices;

using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using Sonos.Base;
using Sonos.Base.Services;
using Sonos.Web.Filters;

internal static class MusicServicesApi
{
    private const string SERVICE_NAME = "MusicServices";
    private const string SERVICE_NAME_KEBAB = "music-services";
    internal static RouteGroupBuilder MapMusicServicesApi(this WebApplication webApplication)
    {
        var group = webApplication
            .MapGroup("/api/speakers/{speakerId}/musicservices")
            .WithTags("UPNP MusicServices")
            .WithGroupName("upnp-music-services");

        group.MapPost("/getsessionid", GetSessionIdAsync)
            .Produces<MusicServicesService.GetSessionIdResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetSessionId", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/listavailableservices", ListAvailableServicesAsync)
            .Produces<MusicServicesService.ListAvailableServicesResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "ListAvailableServices", SERVICE_NAME_KEBAB, "Load music service list as xml")
            .AddSonosServiceExceptionFilter();

        group.MapGet("/updateavailableservices", UpdateAvailableServicesAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "UpdateAvailableServices", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        return group;
    }

    private static async Task<IResult> GetSessionIdAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory GetSessionId body")]MusicServicesService.GetSessionIdRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.MusicServicesService.GetSessionId(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> ListAvailableServicesAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.MusicServicesService.ListAvailableServices(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> UpdateAvailableServicesAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.MusicServicesService.UpdateAvailableServices(cancellationToken);
        return Results.Ok(result);
    }
}
