/*
 * Sonos-net RenderingControlService
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Sonos.Web.SonosServices;

using Microsoft.AspNetCore.Mvc;
using Sonos.Base;
using Sonos.Base.Services;

internal static class RenderingControlApi
{
    private const string SERVICE_NAME = "RenderingControl";
    private const string SERVICE_NAME_KEBAB = "rendering-control";
    internal static void MapRenderingControlApi(this WebApplication webApplication)
    {
        var group = webApplication
            .MapGroup("/api/speakers/{speakerId}/renderingcontrol")
            .WithTags("UPNP RenderingControl")
            .WithGroupName("upnp-rendering-control");

        group.MapGet("/getbass", GetBassAsync)

            .WithSonosServiceDescription(SERVICE_NAME, "GetBass", SERVICE_NAME_KEBAB, "Get bass level between -10 and 10")
            .Produces<RenderingControlService.GetBassResponse>(200);

        group.MapPost("/geteq", GetEQAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetEQ", SERVICE_NAME_KEBAB, "Get equalizer value")
            .Produces<RenderingControlService.GetEQResponse>(200);

        group.MapGet("/getheadphoneconnected", GetHeadphoneConnectedAsync)

            .WithSonosServiceDescription(SERVICE_NAME, "GetHeadphoneConnected", SERVICE_NAME_KEBAB, null)
            .Produces<RenderingControlService.GetHeadphoneConnectedResponse>(200);

        group.MapPost("/getloudness", GetLoudnessAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetLoudness", SERVICE_NAME_KEBAB, "Whether or not Loudness is on")
            .Produces<RenderingControlService.GetLoudnessResponse>(200);

        group.MapPost("/getmute", GetMuteAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetMute", SERVICE_NAME_KEBAB, null)
            .Produces<RenderingControlService.GetMuteResponse>(200);

        group.MapGet("/getoutputfixed", GetOutputFixedAsync)

            .WithSonosServiceDescription(SERVICE_NAME, "GetOutputFixed", SERVICE_NAME_KEBAB, null)
            .Produces<RenderingControlService.GetOutputFixedResponse>(200);

        group.MapGet("/getroomcalibrationstatus", GetRoomCalibrationStatusAsync)

            .WithSonosServiceDescription(SERVICE_NAME, "GetRoomCalibrationStatus", SERVICE_NAME_KEBAB, null)
            .Produces<RenderingControlService.GetRoomCalibrationStatusResponse>(200);

        group.MapGet("/getsupportsoutputfixed", GetSupportsOutputFixedAsync)

            .WithSonosServiceDescription(SERVICE_NAME, "GetSupportsOutputFixed", SERVICE_NAME_KEBAB, null)
            .Produces<RenderingControlService.GetSupportsOutputFixedResponse>(200);

        group.MapGet("/gettreble", GetTrebleAsync)

            .WithSonosServiceDescription(SERVICE_NAME, "GetTreble", SERVICE_NAME_KEBAB, "Get treble")
            .Produces<RenderingControlService.GetTrebleResponse>(200);

        group.MapPost("/getvolume", GetVolumeAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetVolume", SERVICE_NAME_KEBAB, "Get volume")
            .Produces<RenderingControlService.GetVolumeResponse>(200);

        group.MapPost("/getvolumedb", GetVolumeDBAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetVolumeDB", SERVICE_NAME_KEBAB, null)
            .Produces<RenderingControlService.GetVolumeDBResponse>(200);

        group.MapPost("/getvolumedbrange", GetVolumeDBRangeAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetVolumeDBRange", SERVICE_NAME_KEBAB, null)
            .Produces<RenderingControlService.GetVolumeDBRangeResponse>(200);

        group.MapPost("/ramptovolume", RampToVolumeAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "RampToVolume", SERVICE_NAME_KEBAB, null)
            .Produces<RenderingControlService.RampToVolumeResponse>(200);

        group.MapGet("/resetbasiceq", ResetBasicEQAsync)

            .WithSonosServiceDescription(SERVICE_NAME, "ResetBasicEQ", SERVICE_NAME_KEBAB, null)
            .Produces<RenderingControlService.ResetBasicEQResponse>(200);

        group.MapPost("/resetexteq", ResetExtEQAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "ResetExtEQ", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/restorevolumepriortoramp", RestoreVolumePriorToRampAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "RestoreVolumePriorToRamp", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/setbass", SetBassAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetBass", SERVICE_NAME_KEBAB, "Set bass level, between -10 and 10")
            .Produces<bool>(200);

        group.MapPost("/setchannelmap", SetChannelMapAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetChannelMap", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/seteq", SetEQAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetEQ", SERVICE_NAME_KEBAB, "Set equalizer value for different types")
            .Produces<bool>(200);

        group.MapPost("/setloudness", SetLoudnessAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetLoudness", SERVICE_NAME_KEBAB, "Set loudness on / off")
            .Produces<bool>(200);

        group.MapPost("/setmute", SetMuteAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetMute", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/setoutputfixed", SetOutputFixedAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetOutputFixed", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/setrelativevolume", SetRelativeVolumeAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetRelativeVolume", SERVICE_NAME_KEBAB, null)
            .Produces<RenderingControlService.SetRelativeVolumeResponse>(200);

        group.MapPost("/setroomcalibrationstatus", SetRoomCalibrationStatusAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetRoomCalibrationStatus", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/setroomcalibrationx", SetRoomCalibrationXAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetRoomCalibrationX", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/settreble", SetTrebleAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetTreble", SERVICE_NAME_KEBAB, "Set treble level")
            .Produces<bool>(200);

        group.MapPost("/setvolume", SetVolumeAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetVolume", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/setvolumedb", SetVolumeDBAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetVolumeDB", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);
    }

    private static async Task<IResult> GetBassAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.GetBass(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetEQAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.GetEQRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.GetEQ(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetHeadphoneConnectedAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.GetHeadphoneConnected(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetLoudnessAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.GetLoudnessRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.GetLoudness(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetMuteAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.GetMuteRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.GetMute(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetOutputFixedAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.GetOutputFixed(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetRoomCalibrationStatusAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.GetRoomCalibrationStatus(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetSupportsOutputFixedAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.GetSupportsOutputFixed(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetTrebleAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.GetTreble(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.GetVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.GetVolume(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetVolumeDBAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.GetVolumeDBRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.GetVolumeDB(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetVolumeDBRangeAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.GetVolumeDBRangeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.GetVolumeDBRange(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> RampToVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.RampToVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.RampToVolume(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> ResetBasicEQAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.ResetBasicEQ(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> ResetExtEQAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.ResetExtEQRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.ResetExtEQ(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> RestoreVolumePriorToRampAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.RestoreVolumePriorToRampRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.RestoreVolumePriorToRamp(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetBassAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.SetBassRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.SetBass(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetChannelMapAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.SetChannelMapRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.SetChannelMap(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetEQAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.SetEQRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.SetEQ(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetLoudnessAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.SetLoudnessRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.SetLoudness(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetMuteAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.SetMuteRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.SetMute(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetOutputFixedAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.SetOutputFixedRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.SetOutputFixed(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetRelativeVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.SetRelativeVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.SetRelativeVolume(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetRoomCalibrationStatusAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.SetRoomCalibrationStatusRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.SetRoomCalibrationStatus(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetRoomCalibrationXAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.SetRoomCalibrationXRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.SetRoomCalibrationX(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetTrebleAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.SetTrebleRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.SetTreble(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.SetVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.SetVolume(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetVolumeDBAsync(
        [FromRoute]string speakerId,
        [FromBody]RenderingControlService.SetVolumeDBRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.RenderingControlService.SetVolumeDB(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }
}
