/*
 * Sonos-net RenderingControlService
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated/>
namespace Sonos.Web.SonosServices;

using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using Sonos.Base;
using Sonos.Base.Services;
using Sonos.Web.Filters;

internal static class RenderingControlApi
{
    private const string SERVICE_NAME = "RenderingControl";
    private const string SERVICE_NAME_KEBAB = "rendering-control";
    internal static RouteGroupBuilder MapRenderingControlApi(this WebApplication webApplication)
    {
        var group = webApplication
            .MapGroup("/api/speakers/{speakerId}/renderingcontrol")
            .WithTags("UPNP RenderingControl")
            .WithGroupName("upnp-rendering-control");

        group.MapGet("/getbass", GetBassAsync)

            .Produces<RenderingControlService.GetBassResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetBass", SERVICE_NAME_KEBAB, "Get bass level between -10 and 10")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/geteq", GetEQAsync)
            .Produces<RenderingControlService.GetEQResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetEQ", SERVICE_NAME_KEBAB, "Get equalizer value")
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getheadphoneconnected", GetHeadphoneConnectedAsync)

            .Produces<RenderingControlService.GetHeadphoneConnectedResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetHeadphoneConnected", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/getloudness", GetLoudnessAsync)
            .Produces<RenderingControlService.GetLoudnessResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetLoudness", SERVICE_NAME_KEBAB, "Whether or not Loudness is on")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/getmute", GetMuteAsync)
            .Produces<RenderingControlService.GetMuteResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetMute", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getoutputfixed", GetOutputFixedAsync)

            .Produces<RenderingControlService.GetOutputFixedResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetOutputFixed", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getroomcalibrationstatus", GetRoomCalibrationStatusAsync)

            .Produces<RenderingControlService.GetRoomCalibrationStatusResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetRoomCalibrationStatus", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/getsupportsoutputfixed", GetSupportsOutputFixedAsync)

            .Produces<RenderingControlService.GetSupportsOutputFixedResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetSupportsOutputFixed", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/gettreble", GetTrebleAsync)

            .Produces<RenderingControlService.GetTrebleResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetTreble", SERVICE_NAME_KEBAB, "Get treble")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/getvolume", GetVolumeAsync)
            .Produces<RenderingControlService.GetVolumeResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetVolume", SERVICE_NAME_KEBAB, "Get volume")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/getvolumedb", GetVolumeDBAsync)
            .Produces<RenderingControlService.GetVolumeDBResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetVolumeDB", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/getvolumedbrange", GetVolumeDBRangeAsync)
            .Produces<RenderingControlService.GetVolumeDBRangeResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "GetVolumeDBRange", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/ramptovolume", RampToVolumeAsync)
            .Produces<RenderingControlService.RampToVolumeResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "RampToVolume", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/resetbasiceq", ResetBasicEQAsync)

            .Produces<RenderingControlService.ResetBasicEQResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "ResetBasicEQ", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/resetexteq", ResetExtEQAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "ResetExtEQ", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/restorevolumepriortoramp", RestoreVolumePriorToRampAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "RestoreVolumePriorToRamp", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setbass", SetBassAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetBass", SERVICE_NAME_KEBAB, "Set bass level, between -10 and 10")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setchannelmap", SetChannelMapAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetChannelMap", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/seteq", SetEQAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetEQ", SERVICE_NAME_KEBAB, "Set equalizer value for different types")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setloudness", SetLoudnessAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetLoudness", SERVICE_NAME_KEBAB, "Set loudness on / off")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setmute", SetMuteAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetMute", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setoutputfixed", SetOutputFixedAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetOutputFixed", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setrelativevolume", SetRelativeVolumeAsync)
            .Produces<RenderingControlService.SetRelativeVolumeResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetRelativeVolume", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setroomcalibrationstatus", SetRoomCalibrationStatusAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetRoomCalibrationStatus", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setroomcalibrationx", SetRoomCalibrationXAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetRoomCalibrationX", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/settreble", SetTrebleAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetTreble", SERVICE_NAME_KEBAB, "Set treble level")
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setvolume", SetVolumeAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetVolume", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setvolumedb", SetVolumeDBAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetVolumeDB", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        return group;
    }

    private static async Task<IResult> GetBassAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.GetBass(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetEQAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory GetEQ body")]RenderingControlService.GetEQRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.GetEQ(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetHeadphoneConnectedAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.GetHeadphoneConnected(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetLoudnessAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory GetLoudness body")]RenderingControlService.GetLoudnessRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.GetLoudness(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetMuteAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory GetMute body")]RenderingControlService.GetMuteRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.GetMute(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetOutputFixedAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.GetOutputFixed(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetRoomCalibrationStatusAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.GetRoomCalibrationStatus(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetSupportsOutputFixedAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.GetSupportsOutputFixed(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetTrebleAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.GetTreble(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory GetVolume body")]RenderingControlService.GetVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.GetVolume(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetVolumeDBAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory GetVolumeDB body")]RenderingControlService.GetVolumeDBRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.GetVolumeDB(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> GetVolumeDBRangeAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory GetVolumeDBRange body")]RenderingControlService.GetVolumeDBRangeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.GetVolumeDBRange(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> RampToVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory RampToVolume body")]RenderingControlService.RampToVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.RampToVolume(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> ResetBasicEQAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.ResetBasicEQ(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> ResetExtEQAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory ResetExtEQ body")]RenderingControlService.ResetExtEQRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.ResetExtEQ(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> RestoreVolumePriorToRampAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory RestoreVolumePriorToRamp body")]RenderingControlService.RestoreVolumePriorToRampRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.RestoreVolumePriorToRamp(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetBassAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetBass body")]RenderingControlService.SetBassRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.SetBass(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetChannelMapAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetChannelMap body")]RenderingControlService.SetChannelMapRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.SetChannelMap(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetEQAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetEQ body")]RenderingControlService.SetEQRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.SetEQ(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetLoudnessAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetLoudness body")]RenderingControlService.SetLoudnessRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.SetLoudness(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetMuteAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetMute body")]RenderingControlService.SetMuteRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.SetMute(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetOutputFixedAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetOutputFixed body")]RenderingControlService.SetOutputFixedRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.SetOutputFixed(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetRelativeVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetRelativeVolume body")]RenderingControlService.SetRelativeVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.SetRelativeVolume(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetRoomCalibrationStatusAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetRoomCalibrationStatus body")]RenderingControlService.SetRoomCalibrationStatusRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.SetRoomCalibrationStatus(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetRoomCalibrationXAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetRoomCalibrationX body")]RenderingControlService.SetRoomCalibrationXRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.SetRoomCalibrationX(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetTrebleAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetTreble body")]RenderingControlService.SetTrebleRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.SetTreble(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetVolume body")]RenderingControlService.SetVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.SetVolume(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetVolumeDBAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetVolumeDB body")]RenderingControlService.SetVolumeDBRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.RenderingControlService.SetVolumeDB(body, cancellationToken);
        return Results.Ok(result);
    }
}
