/*
 * Sonos-net SystemPropertiesService
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Sonos.Web.SonosServices;

using Microsoft.AspNetCore.Mvc;
using Sonos.Base;
using Sonos.Base.Services;

internal static class SystemPropertiesApi
{
    private const string SERVICE_NAME = "SystemProperties";
    private const string SERVICE_NAME_KEBAB = "system-properties";
    internal static void MapSystemPropertiesApi(this WebApplication webApplication)
    {
        var group = webApplication
            .MapGroup("/api/speakers/{speakerId}/systemproperties")
            .WithTags("UPNP SystemProperties")
            .WithGroupName("upnp-system-properties");

        group.MapPost("/addaccountx", AddAccountXAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "AddAccountX", SERVICE_NAME_KEBAB, null)
            .Produces<SystemPropertiesService.AddAccountXResponse>(200);

        group.MapPost("/addoauthaccountx", AddOAuthAccountXAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "AddOAuthAccountX", SERVICE_NAME_KEBAB, null)
            .Produces<SystemPropertiesService.AddOAuthAccountXResponse>(200);

        group.MapGet("/dopostupdatetasks", DoPostUpdateTasksAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "DoPostUpdateTasks", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/editaccountmd", EditAccountMdAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "EditAccountMd", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/editaccountpasswordx", EditAccountPasswordXAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "EditAccountPasswordX", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/enablerdm", EnableRDMAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "EnableRDM", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapGet("/getrdm", GetRDMAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetRDM", SERVICE_NAME_KEBAB, null)
            .Produces<SystemPropertiesService.GetRDMResponse>(200);

        group.MapPost("/getstring", GetStringAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetString", SERVICE_NAME_KEBAB, "Get a saved string.")
            .Produces<SystemPropertiesService.GetStringResponse>(200);

        group.MapPost("/getwebcode", GetWebCodeAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "GetWebCode", SERVICE_NAME_KEBAB, null)
            .Produces<SystemPropertiesService.GetWebCodeResponse>(200);

        group.MapPost("/provisioncredentialedtrialaccountx", ProvisionCredentialedTrialAccountXAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "ProvisionCredentialedTrialAccountX", SERVICE_NAME_KEBAB, null)
            .Produces<SystemPropertiesService.ProvisionCredentialedTrialAccountXResponse>(200);

        group.MapPost("/refreshaccountcredentialsx", RefreshAccountCredentialsXAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "RefreshAccountCredentialsX", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/remove", RemoveAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "Remove", SERVICE_NAME_KEBAB, "Remove a saved string")
            .Produces<bool>(200);

        group.MapPost("/removeaccount", RemoveAccountAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "RemoveAccount", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/replaceaccountx", ReplaceAccountXAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "ReplaceAccountX", SERVICE_NAME_KEBAB, null)
            .Produces<SystemPropertiesService.ReplaceAccountXResponse>(200);

        group.MapGet("/resetthirdpartycredentials", ResetThirdPartyCredentialsAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "ResetThirdPartyCredentials", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/setaccountnicknamex", SetAccountNicknameXAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetAccountNicknameX", SERVICE_NAME_KEBAB, null)
            .Produces<bool>(200);

        group.MapPost("/setstring", SetStringAsync)
            .WithSonosServiceDescription(SERVICE_NAME, "SetString", SERVICE_NAME_KEBAB, "Save a string in the system")
            .Produces<bool>(200);
    }

    private static async Task<IResult> AddAccountXAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.AddAccountXRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.AddAccountX(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> AddOAuthAccountXAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.AddOAuthAccountXRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.AddOAuthAccountX(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> DoPostUpdateTasksAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.DoPostUpdateTasks(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> EditAccountMdAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.EditAccountMdRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.EditAccountMd(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> EditAccountPasswordXAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.EditAccountPasswordXRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.EditAccountPasswordX(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> EnableRDMAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.EnableRDMRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.EnableRDM(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetRDMAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.GetRDM(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetStringAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.GetStringRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.GetString(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> GetWebCodeAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.GetWebCodeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.GetWebCode(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> ProvisionCredentialedTrialAccountXAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.ProvisionCredentialedTrialAccountXRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.ProvisionCredentialedTrialAccountX(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> RefreshAccountCredentialsXAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.RefreshAccountCredentialsXRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.RefreshAccountCredentialsX(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> RemoveAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.RemoveRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.Remove(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> RemoveAccountAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.RemoveAccountRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.RemoveAccount(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> ReplaceAccountXAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.ReplaceAccountXRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.ReplaceAccountX(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> ResetThirdPartyCredentialsAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.ResetThirdPartyCredentials(cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetAccountNicknameXAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.SetAccountNicknameXRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.SetAccountNicknameX(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }

    private static async Task<IResult> SetStringAsync(
        [FromRoute]string speakerId,
        [FromBody]SystemPropertiesService.SetStringRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }
        try
        {
            var result = await device.SystemPropertiesService.SetString(body, cancellationToken);
            return Results.Ok(result);
        }
        catch (SonosServiceException ex)
        {
            return SonosResults.ServiceExceptionResult(ex);
        }
    }
}
