/*
 * Sonos-net VirtualLineInService
 *
 * File is generated by [@svrooij/sonos-docs](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
 *
 * Repository https://github.com/svrooij/sonos-net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// <auto-generated/>
namespace Sonos.Web.SonosServices;

using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using Sonos.Base;
using Sonos.Base.Services;
using Sonos.Web.Filters;

internal static class VirtualLineInApi
{
    private const string SERVICE_NAME = "VirtualLineIn";
    private const string SERVICE_NAME_KEBAB = "virtual-line-in";
    internal static RouteGroupBuilder MapVirtualLineInApi(this WebApplication webApplication)
    {
        var group = webApplication
            .MapGroup("/api/speakers/{speakerId}/virtuallinein")
            .WithTags("UPNP VirtualLineIn")
            .WithGroupName("upnp-virtual-line-in");

        group.MapGet("/next", NextAsync)

            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "Next", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/pause", PauseAsync)

            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "Pause", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/play", PlayAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "Play", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/previous", PreviousAsync)

            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "Previous", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/setvolume", SetVolumeAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "SetVolume", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/starttransmission", StartTransmissionAsync)
            .Produces<VirtualLineInService.StartTransmissionResponse>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "StartTransmission", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapGet("/stop", StopAsync)

            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "Stop", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        group.MapPost("/stoptransmission", StopTransmissionAsync)
            .Produces<bool>(200)
            .WithSonosServiceDescription(SERVICE_NAME, "StopTransmission", SERVICE_NAME_KEBAB, null)
            .AddSonosServiceExceptionFilter();

        return group;
    }

    private static async Task<IResult> NextAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.VirtualLineInService.Next(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> PauseAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.VirtualLineInService.Pause(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> PlayAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory Play body")]VirtualLineInService.PlayRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.VirtualLineInService.Play(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> PreviousAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.VirtualLineInService.Previous(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> SetVolumeAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory SetVolume body")]VirtualLineInService.SetVolumeRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.VirtualLineInService.SetVolume(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> StartTransmissionAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory StartTransmission body")]VirtualLineInService.StartTransmissionRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.VirtualLineInService.StartTransmission(body, cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> StopAsync(
        [FromRoute]string speakerId,
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.VirtualLineInService.Stop(cancellationToken);
        return Results.Ok(result);
    }

    private static async Task<IResult> StopTransmissionAsync(
        [FromRoute]string speakerId,
        [FromBody, Description("Mandatory StopTransmission body")]VirtualLineInService.StopTransmissionRequest body, 
        [FromServices]SonosManager sonosManager,
        CancellationToken cancellationToken)
    {
        var device = sonosManager.GetSonosDevice(speakerId);
        if (device == null)
        {
            return SonosResults.DeviceNotFoundResult(speakerId);
        }

        var result = await device.VirtualLineInService.StopTransmission(body, cancellationToken);
        return Results.Ok(result);
    }
}
